modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/LCLPYT/CoreBase/issues"
displayURL="https://github.com/LCLPYT/CoreBase"
authors="LCLP"
license="MIT"

[[mods]]
    modId="corebase"
    version="${version}"
    displayName="CoreBase"
    updateJSONURL="https://raw.githubusercontent.com/LCLPYT/CoreBase/master/CoreBase/update.json"
    logoFile="logo.png"
    credits="LCLPNetwork!"
    description='''
    A base for modding by LCLP.
    '''
    
    [[dependencies.corebase]]
        modId="forge"
        mandatory=true
        versionRange="[34,)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.corebase]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.16.3]"
        ordering="NONE"
        side="BOTH"

